nowsecure/node-applesign

depsolver.js

The program fails when the binary does not have any library linked. A comparison has been added in order to check if there is any library before extracting any lib reference.

Fix issue when binaries does not have libraries linked

---

bin/applesign.js
index.js
session.js

-K [NAME] to add a custom group name, this will be automatically prefixed with team identifier
-B to add a group named after the bundle identifier (the one from Info.plist or the one passed in -b),
also this one will be prefixed with team identifier
These are injected also when cloning entitlements from provisioning profile.

Add options to inject keychain access groups

---

session.js

Otherwise it will result in a failure during installation for invalid entitlements - because the renamed groups don't belong to the provisioning profile we're cloning entitlements from.

Avoid renaming app groups if -c and -m are passed

---

index.js

Config needs to be specified to inject the library. Before, unspecified bin has been passed to `insertLibrary`

Fix injection of libraries

---

index.js

The following condition never allowed the block to execute when we pass false as an argument.
> if (this.config.withGetTaskAllow) {

override the withGetTaskAllow from the config

---

index.js
lib/config.js

This change adds back the code that preserved XCTest files when the Plugins directory is deleted, but controls it via the option `-x`: when specified alone, all plugins except XCTest files are removed; when specified with -w it will preserve the XCTest files instead of removing the entire Plugins directory.
I didn't look through all the commit history for this part of the code, so there may be better (more recent) code that would be preferable to restore.

Resurrect the old -w behavior via -x to keep XCTests

---

index.js
lib/config.js

This feature has been requested for a couple of years already, and the only reason for not having it was a simple interface for managing all the possible use cases. In order to move forward i just implemented -j which allows to override with an inline json string the signing options for files matching specific attributes, here's an example:
```json
{
"custom": [
{
"filematch": "RegexMatchExpr$",
"entitlements": "/tmp/custom-entitlements.plist",
"identity": "89312489X",
"keychain": "/tmp/custom-keychain.db"
}
]
}
```
The only required key in here is `filematch` which is used by signFile to determine which files needs to use custom signing options. The entitlements, identity and keychain path fields are optional. those will override the default signing attributes when matching.
This is …

Add -j to specify a JSON with custom signing options

---

index.js

It appears that Watch apps can be bundled into a directory called `com.apple.WatchPlaceholder`.  This change removes that directory when `-w` is specified.

Remove com.apple.WatchPlaceholder directory when -w is specified

---

index.js
lib/appdir.js

This change does two things:
* When an appex is signed, it is removed from the list of things to sign in a later step
* When creating the list of libraries, add the main executable first and then the appexs instead of the reverse

Fix signing order

---

index.js

Currently if an error is caught in `signIPA` it is not re-thrown.  As a result, if someone is using the API they will not be able to catch and respond properly to errors - it will appear that the function succeeds (outside of the error being logged).

Throw errors so API use can catch them

---

index.js

When an app has null entitlements and also uses `-c` to clone entitlements, an error occurs when adjusting entitlements:
```
TypeError: Cannot read property 'toString' of null
at Applesign.adjustEntitlementsSync (/Users/blah/node-applesign/index.js:305:36)
at Applesign.adjustEntitlements (/Users/blah/node-applesign/index.js:465:10)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
This changes ensures that entitlements are not null prior to parsing them.

Handle null entitlements when using -c

---

index.js
lib/config.js
lib/tools.js

Used `-Z` because the meaningful part of the alphabet was already taken 😅.
With this change `bin/applesign -Z` just pseudo-signs the input IPA without the need to specify a mobile provisioning profile and preserves the entitlements as they are. Potentially, it's possible to further extend this and also merge in additional entitlements.

Add option to pseudo-sign using ldid2

---

bin/applesign.js
lib/tools.js

Throw on non-existent tools only when trying to use them.
Related to: https://github.com/nowsecure/node-applesign/issues/115

Check tools existence lazily

---

index.js
lib/tools.js

Fix an issue in the pseudo-signing implementation for which it failed to preserve the entitlements, and also failed to sign at all when entitlements are not required. TLDR: fix a total failure, sorry.

Retain entitlements when pseudo signing

---

index.js

While trying to reproduce #113 I observed the following using a free developer account:
- When using just `-m`, `-c`, and `-a`, installing the re-signed ipa would fail with complaints about `application-identifier` and `keychain-access-groups` in the logs.  Adding `-b` with the bundle ID in my mobileprovision file fixed it and I advised the original reporter to try that.
- When using the above without `-c`, installing would fail and there would be no entitlements in the app binary.  I traced that to a typo `config.entitlements` instead of `config.entitlement`, fixed in this PR.
- After that fix, the ipa would still fail to install without `-c`.  I made two changes to fix that:
- Stopped removing the `com.apple.developer.team-identifier` since it is actually set to the one in the …

Fix for empty entitlements and delete keychain-access-groups when not cloned

---

lib/info-plist.js

This replaces `Object.isObject` (which doesn't exist) with something that should be accurate enough for this purpose.

Object detection fix

---

bin/applesign.js
index.js
lib/tools.js

- don't swallow errors in `signIPA()`
- make `findInPath()` implicit in `getTool()` and idempotent

Improve error handling when used via JS APIs

---

lib/appdir.js

If there is no executable for applesign to sign, a type error is thrown because `undefined` is passed to `path.join`. 
Checking to make sure `apexInfo.CFBundleExecutable` is not undefined before continuing appears to fix this

fix: ensure apexInfo.CFBundleExecutable is truthy before use

---

index.js

By mirroring the full path under the temp directory instead of just the base name (function renamed for clarity).

Fix tmp file name clash when writing entitlements

---

lib/bin.js
lib/tools.js

So we don't depend on `codesign` for this

Get codesign identifier from macho

---

package-lock.json

Apply fixes for the following:
```
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix`
node_modules/braces
cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn
node_modules/npm/node_modules/cross-spawn
ip  *
Severity: high
NPM IP package incorrectly identifies some private IP addresses as public - https://github.com/advisories/GHSA-78xj-cgh5-2h22
ip SSRF improper categorization in isPublic - https://github.com/advisories/GHSA-2p57-rm9w-gvfp
fix available via `npm audit fix`
node_modules/npm/node_modules/ip
socks  1.0.0 - …
```

chore: apply npm audit fixes
